GET http://localhost:3000/product/show

###
POST http://localhost:3000/auth/signup
Content-Type: application/json

{
  "name": "test",
  "email": "name@example.com",
  "password": "password",
  "phone": "12345678911"
}

###
POST http://localhost:3000/auth/login
Content-Type: application/json

{
  "email": "name@example.com",
  "password": "password"
}
