POST http://localhost:3000/product
Content-Type: application/json

{
  "category_id": "628ce058be94a071c96c890d",
  "name": "JProduct 1",
  "description": "JProduct 1 description",
  "price": "100.00",
  "sku": "JP-1",
  "quantity": "10"
}

###
